### ISSUE TITLE
Please remove my ID

### ISSUE THREAD

**Issue by pejakm** [Tox/toxme.se#14]
I registered my nameusername (`pejakm`) via Antox, but I forgot password. Now I can't acces my data at toxme.se, and I have new ID which I would like to register. Please remove my old one so I can register the new ID.

Old ID: F2F321EBB4AE2B9E61023061EA1ED1ED6EB995754C54611C857E0EA1C6423F7B96E9E439F00A

**Comment by jontis** [comment]
Same here. I'm used to qtox, downloaded antox and without knowing how it worked registered.
I had some problems with the antox nightlies so I had to uninstall before reinstalling, without thinking about that it would delete all data so know, I'm unable to reach my profile, and does not have password.

My thought on this is, I understand that you can't know who the profile belongs too, but could you just auto remove unused profiles? Like profiles that have not been used for a month, or profiles that were created and used for a day and then left for a month?

I figure you would want to clean the database in some way to free up registered but forgotten names?
Let's find a way to do it.

Maybe a manual: free up my lost profile where you enter your name, and if it has not been used for a month, it is deleted?

**Comment by TheLastProject** [comment]
@jontis Automatically removing unused profiles isn't possible, as profiles are never truly used. The only thing toxme.se does is, when you ask for jontis@toxme.se, tell you the Tox ID that the client needs to add to send you a friend request.

**Comment by jontis** [comment]
Ok, thanks for explaining.
