### ISSUE TITLE
Copyright is 2014 still

### ISSUE THREAD

**Issue by dcharles525** [Tox/toxme.se#21]
Title says it all

**Comment by urras** [comment]
I thought I updated it in ff35a56, but I'm not sure if @stqism has updated it server-side yet.

**Comment by nurupo** [comment]
Don't think he will update it for next 5 years, with such attitude.

>&lt;AlexStraunoff&gt; nurupo, First rule of enterprise: don't upgrade anything ever
>...
>&lt;AlexStraunoff&gt; nurupo, No, I just have to test the next minor version for 5 more years before we're able to ensure it won't break anything obivously

**Comment by dcharles525** [comment]
Its such a simple change, or you could just make the year automatically change with HTML5 or Javascript, so we don't have to deal with this...

**Comment by stqism** [comment]
@nurupo 
Your ability to take jokes about other things and use them totally out of context is outstanding. 

Funny enough it's fixed in the actual code, problem is I broke git so it's fairly hard to merge things like that except by hand.

**Comment by urras** [comment]
@stqism Well, We would appreciate it if you merged these changes by hand. Also, do you think you could add a Jenkins Job that updates toxme.se when changes are pushed (much like [the blog](https://jenkins.libtoxcore.so/job/Deploy%20blog/) and [Tox.im](https://jenkins.libtoxcore.so/job/tox.im%20assets%20push/)?

**Comment by dcharles525** [comment]
Yeah I was not trying to be a dick, thanks for working on this @urras and @stqism.

**Comment by stqism** [comment]
@urras toxme is fairly mission-critical, not one of those things I'd like to potentially auto-break.

What I do for tox.im is fairly neat, it gets pulled to a special staging site for a couple hours where we can play with changes before they go live. 


Also, fixing toxme would mean fixing the git repo :)

**Comment by urras** [comment]
@stqism what's wrong with the git repo?

**Comment by stal888** [comment]
> toxme is fairly mission-critical
> still hasn't added redundancy

![ayy](https://cloud.githubusercontent.com/assets/774591/5986370/f81cf86e-a8a9-11e4-8ab8-c5595aadb938.jpg)

**Comment by urras** [comment]
@stqism Can you fix this soon please? It's been quite a while...

**Comment by stqism** [comment]
Guess what super critical game breaking bug just got fixed?

**Comment by itsrachelfish** [comment]
omg @stqism I am so proud of you :heart:
