### ISSUE TITLE
Add a way to make multiple aliases for one name

### ISSUE THREAD

**Issue by donkus** [Tox/toxme.se#24]
I was thinking something like add/remove button for aliases in the signup/edit form, and a radio button for which one is the default.
Aliases would consist of one name and one ID.
donkus:pc@toxme.se could resolve to an ID on my PC.
donkus:droid@toxme.se could resolve to an ID on Antox.
I could select "pc" as my default alias, meaning donkus@toxme.se would resolve to whatever donkus:pc's ID was.
There wouldn't have to be any update push for this feature to the clients, only toxme.se.

**Comment by stqism** [comment]
We're not doing this as it isn't part of the single Tox standard.
