### ISSUE TITLE
Gsoc 2015 

### ISSUE THREAD

**Issue by milapbhojak** [Tox/toxme.se#25]
I'm milap from india. I would love to contribute on ToxME - Major improvements project as a GSOC participant. I've seen below thing on GSOC idea page it would be great it someone would help me to get started.

Major improvements

Brief explanation: A lot of the initial design of toxme was rushed and not as complete as we like. Because of this, stuff like overaggressive caching makes it hard to distribute and searching lacks features like lookups by location and email. Your task would be to fix this from the ground up, replacing sqlalchemy with a proper replicating database, adding entries like location and email, and implementing searching.

Tips: Being Python, it's fairly easy to underestimate how much work is actually required.

Expected results:
Switch toxme to a new replicating DB
Find a way to transfer data between the existing sqlite db and it
Safely add support for location/email/etc
Work out a way to validate and correct user supplied info (email, checking and fixing locations, etc)
design a UI and a backend to search through this data based on user privacy settings
If time permits work out a Tox bot to do authentication/ownership of an ID to allow resets if one forgets his/her password

**Comment by nurupo** [comment]
Please contact the person that mentors the GSoC project idea directly, instead of creating a bugreport about it.

**Comment by stal888** [comment]
haha good luck

Replacing the database implementation is easy. You just have to preserve the API of User objects (see StaleUser for cleaner code).

**Comment by milapbhojak** [comment]
@nurupo I've sent couple of emails but I couldn't get any reply so I've posted here. and still I'm waiting for Sean's reply. :(

Thanks @stal888 :)

**Comment by urras** [comment]
@stqism
