### ISSUE TITLE
#@toxme.se cannot be viewed

### ISSUE THREAD

**Issue by TheLastProject** [Tox/toxme.se#27]
Someone registered #@toxme.se, giving them https://toxme.se/u/# as user page. # is the HTML thing for ID, which isn't sent to the server, making their page invisible.
![#](https://cloud.githubusercontent.com/assets/1885159/7178229/81da6b5e-e42d-11e4-8aa3-266c45c0fd07.png)

Maybe it's time to add sane nick limitations so people can't break the application

**Comment by Calinou** [comment]
Only A-Z a-z 0-9 -_ should be allowed.

**Comment by stal888** [comment]
Maybe it's time to url-encode links

**Comment by stqism** [comment]
This is a totally valid ToxMe name according to the Tox3 standards.

What does need to be done is URL encoding (see: https://toxme.se/u/%23)

**Comment by stqism** [comment]
[Marked as toxme-5](https://issues.tox.im/youtrack/issue/toxme-5)
