### ISSUE TITLE
Trackability of new issues on the 'issues.tox.im' domain for regular users

### ISSUE THREAD

**Issue by sebie** [Tox/toxme.se#30]
How can regular users track new Tox issues on the issues.tox.im domain, if it is not publicly available?

/cc to my old issue #22 | [toxme-2](https://issues.tox.im/youtrack/issue/toxme-2)

**Comment by sebie** [comment]
Bump?

**Comment by itsrachelfish** [comment]
@sebie tox.im is no longer controlled by the tox developers, please refer to the news post on the new tox website: https://blog.tox.chat/

**Comment by sebie** [comment]
Thank you for the update @itsrachelfish , I had no clue what had happend.

Is Tox being developed on the "ToxMe" or "Tox" organisation?

**Comment by itsrachelfish** [comment]
@sebie Fortunately the real developers for tox still have control of the "Tox" organization. The "ToxMe" organization was created by @stqism after he got kicked out.

Unfortunately the ToxMe domain name is still controlled by @stqism and there's nothing we can do besides suggest you use http://register.utox.org/ instead.

**Comment by itsrachelfish** [comment]
@sebie I've reopened your original issue, so I'm going to close this one. You're right, moving issues to a separate service instead of using GitHub doesn't make sense.

Your original issue is still valid, since there is still no way to recover passwords.

**Comment by sebie** [comment]
@itsrachelfish Thanks for your understanding. I just hope this recent drama doesn't break Tox down. 

>Is Tox being developed on the "ToxMe" or "Tox" organisation?

To confirm, it is the Tox organisation. Correct?

**Comment by itsrachelfish** [comment]
@sebie All development will continue here at the Tox organization, however someone will probably need to get a new domain name for the project...

**Comment by stqism** [comment]
@itsrachelfish, darling, I'm also the current only maintainer of the codebase.

**Comment by stqism** [comment]
@itsrachelfish, darling, I'm also the current and only maintainer of the codebase. 

And by the way, doll, I'd appreciate not having my responses removed when they make you look bad.

**Comment by optimumtact** [comment]
Treating someone with some basic respect might help, but then you being a socio-path I wouldn't expect that anyway.

**Comment by hexafluoride** [comment]
itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo Kappa

**Comment by hexafluoride** [comment]
itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo itsudemoo Kappa
